---
title: "HW5"
author: "aliya yakupova"
date: "1/7/2021"
output: html_document
---

```{r env_a, include=FALSE}
#install.packages('tidyverse')
#install.packages("ggplot2")
library("tidyr")
library("ggplot2")
```

# Visuals pt.1

## Task A

First transform iris dataset to iris_long dataset.

Let's have a look at the result of 
```{r transform, echo=FALSE}
iris_long <- iris %>%
  pivot_longer(cols = -Species, names_sep = "\\.", names_to = c("Part", ".value"))

iris_long <- data.frame(iris_long)
str(iris_long)
head(iris_long)
```

Now let's plot our data

```{r iris_plot, echo=FALSE}
ggplot(iris_long, aes(x = Length,
                      y = Width,
                      color = Part)) +
  geom_point()
```

## Task B
## 1

```{r env_b, include=FALSE}
# install.packages("gapminder")
library("gapminder")
library("dplyr")
```

```{r gapminder_plot1, echo=FALSE}
gapminder %>%
  filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap,
             y = lifeExp,
             color = continent,
             size = pop)) +
  geom_point()+
  scale_x_log10()
```

## 2
```{r gapminder_plot2, echo=FALSE}
gapminder %>%
  group_by(year, continent) %>%
  summarise(meanLifeExp = mean(lifeExp), year, continent, totalPopulation = sum(as.numeric(pop)), .groups = 'drop') %>%
  ggplot(aes(x = year,
             y = meanLifeExp,
             color = continent,
             size = totalPopulation)) +
  geom_point() +
  geom_line(size = 0.5)
```

## 3
```{r gapminder_plot3, echo=FALSE}
gapminder %>%
  group_by(continent) %>%
  summarise(meanLifeExp = mean(lifeExp), continent, .groups = 'drop') %>%
  ggplot(aes(x = meanLifeExp,
             fill = continent)) +
  geom_bar(position = "stack")

#str(gapminder)
```