---
title: "hw3"
author: "aliya yakupova"
date: "12/7/2020"
output: html_document
---
#сделать в маркдауне, конвертировать в числа столбцы, проверить почему Input `PrecipitationIn` is `as.numeric(PrecipitationIn)`. не конвертируется в число (сортировать по убыванию, возрастанию)

library(tidyr)
install.packages('stringr')
library(stringr)

weather <- readRDS("~/R_HW/weather.rds")


weather_clean <- gather(weather, key = day, value = val, X1:X31, na.rm = TRUE)
                 
head(weather_clean)

weather_clean <- weather_clean[, -1]
head(weather_clean)

weather_clean <- spread(weather_clean, key = measure, value = val)
head(weather_clean)

weather_clean$day <- str_replace(weather_clean$day, "X", "")
head(weather_clean)

weather_clean <- unite(weather_clean, col = date, day, month, year, sep = "-")
head(weather_clean)

summary(weather_clean)
any(is.na(weather_clean))
na.omit(weather_clean)
complete.cases(weather_clean)
str(weather_clean)

install.packages('tidyverse')
library(tidyr)
library(dplyr)
weather_clean <- mutate_at(weather_clean, vars(CloudCover, Max.Dew.PointF:WindDirDegrees), funs(as.numeric))
head(weather_clean)